name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy getanswer-staging \
              --gen2 \
              --runtime=python310 \
              --memory=4GB \
              --region=us-east1 \
              --source=packages/googlecloud/functions/getanswer \
              --entry-point=getanswer \
              --trigger-http \
              --allow-unauthenticated \
              --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_STAGING }}
